### ISSUE TITLE
where do ID_SIGNINGSCENARIO_* come from?

### ISSUE THREAD

**Issue by HyperSine** [Wack0/SecureBootPolicyTools#1]
hi, I very appreciate your work. I'm developing a tool to convert sipolicy.p7b back to xml format. The file `SecureBootPolicy/SecureBootPolicy/Constants.cs` gives me a lot of information about mapping between raw value and signing scenario. But I'd like to ask, where do these ID_SIGNINGSCENARIO_* come from? How do you get that?

**Comment by Wack0** [comment]
If you mean the constants themselves: from all boot environment binaries and ci.dll/skci.dll

If you mean the names: those < 0x80 are identical to SE_SIGNING_LEVEL_* from winnt.h; those starting from 0x80 come from reversing + private symbols :)

**Comment by HyperSine** [comment]
Ok, I see. Thanks.
